#!/usr/bin/env bash

# build tool

case $1 in
    "update" | "u")
        ./scripts/update-submodules.sh
        ;;
    "patch" | "p")
        ./scripts/apply-patches.sh
        ;;
    "create-patch" | "c")
        ./scripts/create-patches.sh "$2"
        ;;
    "reset" | "r")
        ./scripts/reset-submodules.sh
        ;;
    "build" | "b")
        ./scripts/build-docker.sh "$2" "$3"
        ;;
    "run")
        ./scripts/run.sh
        ;;
    "install" | "i")
        ./scripts/install-deps.sh
        ;;
    *)
    echo "This is the build tool for tools website project. It provides various commands to manage the projects in this repository."
    echo ""
    echo "Commands:"
    echo "  $0 u, update - updates all submodules from upstream"
    echo "  $0 p, patch - applies all patches in the patches directory to the corresponding projects"
    echo "  $0 c, create-patch - generates patch files for all changes in the specified project"
    echo "  $0 r, reset - resets all submodules to a clean state, discarding any local changes"
    echo "  $0 b, build <tag> [--publish|-p] - applies patches, builds the Docker image, and optionally publishes it"
    echo "  $0 i, install - installs dependencies in all submodules and the frontend"
    echo "  $0 run <tag> - builds and runs the docker image"
    echo "  $0 help - displays this help message"
    echo ""
esac
