server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/main-frontend;
    index index.html;

    autoindex off;

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }
    #------------------------Swagger API Docs------------------------

    location = /api-docs {
        return 301 /api-docs/;
    }

    location /api-docs/ {
        alias /usr/share/nginx/html/api-docs/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    #------------------------GitRSS------------------------

    location = /gitrss {
        return 301 /gitrss/;
    }

    location = /gitrss/api {
        return 301 /gitrss/api/;
    }

    location /gitrss/ {
        alias /usr/share/nginx/html/gitrss/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /gitrss/api/ {
        proxy_pass http://127.0.0.1:3000/;
    }

    #------------------------Package JSON Analyzer------------------------

    location = /package-json-analyzer {
        return 301 /package-json-analyzer/;
    }

    location = /package-json-analyzer/api {
        return 301 /package-json-analyzer/api/;
    }

    location /package-json-analyzer/ {
        alias /usr/share/nginx/html/package-json-analyzer/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /package-json-analyzer/api/ {
        proxy_pass http://127.0.0.1:3001/;
    }

    #------------------------OpenAPI Merger------------------------

    location = /openapi-merger {
        return 301 /openapi-merger/;
    }

    location = /openapi-merger/api {
        return 301 /openapi-merger/api/;
    }

    location /openapi-merger/ {
        alias /usr/share/nginx/html/openapi-merger/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /openapi-merger/api/ {
        proxy_pass http://127.0.0.1:3002/;
    }
}