type TermsSection = {
  id: string;
  title: string;
  body: string;
};

const termsSection: TermsSection[] = [
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    body: "Users are expected to use the platform and its tools responsibly. Any misuse, disruptive behavior, or activity that negatively affects the platform, infrastructure, services, or other users is prohibited.",
  },
  {
    id: "uptime",
    title: "Service Availability",
    body: 'Services, APIs, and tools are provided on an "as is" and "as available" basis. No guarantee is made regarding uptime, uninterrupted availability, reliability, or error-free operation.',
  },
  {
    id: "api-usage",
    title: "API Usage",
    body: "Excessive requests, automated abuse, scraping, rate-limit bypass attempts, or other forms of API misuse may result in temporary or permanent access restrictions.",
  },
  {
    id: "abuse",
    title: "Abuse Prevention",
    body: "Abuse of the platform, APIs, or services in any form is strictly prohibited. This includes actions that place excessive load on the infrastructure or interfere with normal platform operation.",
  },
  {
    id: "tool-results",
    title: "Generated Results",
    body: "Outputs generated by tools provided on the platform may be incomplete, inaccurate, outdated, or unavailable. Users are responsible for verifying any generated results before relying on them.",
  },
  {
    id: "limitations",
    title: "Service Limitations",
    body: "Certain services may include request limits, payload restrictions, cooldowns, or other technical protections. Attempts to bypass these limitations are prohibited.",
  },
  {
    id: "enforcement",
    title: "Enforcement Actions",
    body: "Violation of these terms may result in rate limiting, temporary suspension, permanent bans, or other access restrictions without prior notice.",
  },
  {
    id: "changes",
    title: "Service Changes",
    body: "Features, APIs, tools, and related functionality may be changed, restricted, or removed at any time without notice.",
  },
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    body: "By accessing or using the platform and its services, users acknowledge and agree to these terms.",
  },
];

const lastUpdated = "2026-04-26";

export const metadata = {
  title: "Petar_mc's Tools | Terms",
  description: "Terms of Service for Petar_mc's Tools platform.",
  robots: {
    index: false,
    follow: false,
  },
  alternates: {
    canonical: "https://tools.ptrmc.net/terms",
  },
  openGraph: {
    title: "Petar_mc's Tools | Terms",
    url: "https://tools.ptrmc.net/terms",
    type: "website",
  },
};

export default function TermsPage() {
  return (
    <section className="card static-page" aria-labelledby="terms-title">
      <h2 id="terms-title" className="static-page_title">
        Terms of Service
      </h2>

      <p className="static-page_updated">Last updated: {lastUpdated}</p>

      <ol className="terms-list">
        {termsSection.map((section) => (
          <li key={section.id}>
            <h3>{section.title}</h3>
            <p>{section.body}</p>
          </li>
        ))}
      </ol>

      <p>
        By using the service, you acknowledge and accept these conditions.
      </p>

      <h2 className="static-page_title">Project Specific Terms</h2>

      <p className="static-page_description">
        Each individual tool or project may have its own specific terms of
        service, usage guidelines, or disclaimers. Please refer to the
        respective documentation for each tool.
        <br />
        <br />
        While each tool may have its own specific terms, the general terms
        listed above apply to all services on the platform.
      </p>
    </section>
  );
}